services:
  init-website-get-orga-niced:
    image: busybox:1.36
    container_name: init-website-get-orga-niced
    command: sh -c "chown -R ${PUID}:${GUID} /data && chmod -R 755 /data"
    volumes:
      - ${WEB_CONTENT_PATH}:/data
    network_mode: none
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true

  website-get-orga-niced:
    image: nginxinc/nginx-unprivileged:alpine
    container_name: website-get-orga-niced
    user: "${PUID}:${GUID}"
    restart: unless-stopped

    depends_on:
      init-website-get-orga-niced:
        condition: service_completed_successfully
    env_file:
      - ../../.env
      - .env

    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

    volumes:
      - ${WEB_CONTENT_PATH}:/usr/share/nginx/html:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-get-orga-niced.rule=${HOST_RULE}"
      - "traefik.http.routers.web-get-orga-niced.entrypoints=websecure"
      - "traefik.http.routers.web-get-orga-niced.tls.certresolver=myresolver"
      - "traefik.http.routers.web-get-orga-niced.middlewares=sec-public@file" 
      - "traefik.http.services.web-get-orga-niced.loadbalancer.server.port=8080"

    networks:
      - traefik-public

    healthcheck:
      #test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  traefik-public:
    name: traefik-public
