services:
  website-aaronsoft:
    image: nginxinc/nginx-unprivileged:alpine
    container_name: website-aaronsoft
    user: "${PUID}:${GUID}"
    restart: unless-stopped

    env_file:
      - ../../.env
      - .env

    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

    volumes:
      - ${WEB_CONTENT_PATH}:/usr/share/nginx/html:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-aaronsoft.rule=${HOST_RULE}"
      - "traefik.http.routers.web-aaronsoft.entrypoints=websecure"
      - "traefik.http.routers.web-aaronsoft.tls.certresolver=myresolver"
      - "traefik.http.routers.web-aaronsoft.middlewares=sec-public@file" 
      - "traefik.http.services.web-aaronsoft.loadbalancer.server.port=8080"

    networks:
      - traefik-public

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  traefik-public:
    name: traefik-public