services:
  # Fix file permissions at startup
  init-sftpgo:
    image: busybox:1.36
    container_name: init-sftpgo
    command: sh -c "chown ${PUID}:${GUID} /etc/sftpgo/users.json && chmod 600 /etc/sftpgo/users.json && chown -R ${PUID}:${GUID} /var/lib/sftpgo"
    volumes:
      - ./users.json:/etc/sftpgo/users.json
      - ./data:/var/lib/sftpgo
    network_mode: none
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
    security_opt:
      - no-new-privileges:true

  sftpgo:
    image: drakkan/sftpgo:v2-alpine
    container_name: sftpgo-gateway
    
    user: "${PUID}:${GUID}"
    depends_on:
      init-sftpgo:
        condition: service_completed_successfully
    restart: unless-stopped
    
    env_file:
      - ../../.env
    
    cap_drop:
      - ALL
    
    security_opt:
      - no-new-privileges:true
      
    read_only: true
    
    tmpfs:
      - /tmp
      - /var/cache/sftpgo 
    
    environment:
      - SFTPGO_LOADDATA_FROM=/etc/sftpgo/users.json
      - SFTPGO_LOADDATA_MODE=1 # 1 = Overwrite existing users from file
      - SFTPGO_SFTPD__BINDINGS__0__PORT=2022
      - SFTPGO_HTTPD__BINDINGS__0__PORT=0 
      - SFTPGO_SFTPD__HOST_KEYS__0=/var/lib/sftpgo/id_rsa
      - SFTPGO_SFTPD__HOST_KEYS__1=/var/lib/sftpgo/id_ecdsa
      - SFTPGO_SFTPD__HOST_KEYS__2=/var/lib/sftpgo/id_ed25519
      
    network_mode: bridge

    ports:
      - "2222:2022"
      
    volumes:
      - ./users.json:/etc/sftpgo/users.json:ro
      - ./data:/var/lib/sftpgo
      - ../../apps/website-aaronsoft/html:/srv/sftp/aaronsoft:rw
      - ../../apps/website-get-orga-niced/html:/srv/sftp/get-orga-niced:rw