# --- Listener Setup ---
listener 1883
allow_anonymous false
password_file /mosquitto/config/mosquitto_passwd

# --- Persistence Settings ---
persistence true
persistence_location /mosquitto/data/

# --- Logging (Docker Stdout) ---
log_dest stdout